"""Add index and uniq check

Revision ID: 1f931949afaa
Revises: ab373345d403
Create Date: 2026-02-22 23:45:07.983843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f931949afaa'
down_revision: Union[str, Sequence[str], None] = 'ab373345d403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ticker_created', 'ticker_prices', ['ticker', 'created_at'], unique=False)
    op.create_unique_constraint('uq_ticker_created_at', 'ticker_prices', ['ticker', 'created_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ticker_created_at', 'ticker_prices', type_='unique')
    op.drop_index('ix_ticker_created', table_name='ticker_prices')
    # ### end Alembic commands ###
